version: '3.8'

services:
  frontend:
    build:
      context: ../../frontend
      dockerfile: ../infrastructure/docker/frontend/Dockerfile
    container_name: ehr-frontend
    ports:
      - "3000:3000"
    volumes:
      - ../../frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - ehr-network

  backend:
    build:
      context: ../../backend
      dockerfile: ../infrastructure/docker/backend/Dockerfile
    container_name: ehr-backend
    ports:
      - "5000:5000"
    volumes:
      - ../../backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
      - JWT_SECRET=your_jwt_secret_here
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/ehr
      - MONGODB_URI=mongodb://mongo:27017/ehr
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - mongo
      - redis
    networks:
      - ehr-network

  postgres:
    image: postgres:15
    container_name: ehr-postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ehr
    networks:
      - ehr-network

  mongo:
    image: mongo:6
    container_name: ehr-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - ehr-network

  redis:
    image: redis:7
    container_name: ehr-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ehr-network

  elasticsearch:
    image: elasticsearch:8.7.0
    container_name: ehr-elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - ehr-network

  kibana:
    image: kibana:8.7.0
    container_name: ehr-kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - ehr-network

networks:
  ehr-network:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
  redis_data:
  elasticsearch_data:
